// Create functionality that will

// CREATE ELEMENTS CONTAINING AFFILIATE LINKS THAT WILL BE ADDED AT THE BOTTOM OF THE PAGE
function addElement(){
	
}



// DELETE ELEMENTS FROM BODY OF PAGE AFTER USER HAS RETURNED AND CLICKED THROUGH TO AMAZON